### ISSUE TITLE
No footprint for capacitor CM2

### ISSUE THREAD

**Issue by KenLagoni** [eugmes/ax5243-test-board#3]
This capacitor is not mounted when frequency is 169MHz, but If one wish to use this PCB with other frequency’s then capacitor CM2 (from datasheet page 33) is missing.

**Comment by eugmes** [comment]
I guess I can add that capacitor, but I was making this board to see if ax5243 can be used to receive AIS signal, and given that it works for me now, I don't expect to be making new versions of this board any time soon.

**Comment by KenLagoni** [comment]
Nice that you managed to get it working as AIS receiver, I'm trying to build an EPIRB receiver using this PCB.

**Comment by eugmes** [comment]
I've added the capacitor now and regenerated gerbers/placement/schematic files. This passes DRC, but otherwise untested. Also, I'll be very interested to know how your project goes.
